### PR TITLE
Push Channels

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

File: Spec/PushChannel.swift [hunk 1]
```diff
@@ -0,0 +1,330 @@
...
+                            guard let error = error else {
+                                fail("Error is nil"); done(); return
+                            }
+                            expect(error.message).to(contain("null client ID"))
+                            done()
+                        }
+                    }
+                }
+
+                // RSH7a2
```
Comment (funkyboy) [inline Spec/PushChannel.swift]: I think this is `RSH7b2`

File: Spec/PushChannel.swift [hunk 2]
```diff
@@ -0,0 +1,330 @@
...
+
+                    expect(query).to(haveParam("deviceId", withValue: params["deviceId"]))
+                    expect(query).toNot(haveParam("clientId", withValue: rest.device.clientId))
+                    expect(query).to(haveParam("channel", withValue: params["channel"]))
+                    expect(query).to(haveParam("concatFilters", withValue: "true"))
+                }
+
+                it("should return a paginated result with PushChannelSubscription filtered by channel and client") {
+                    let params = [
+                        "clientId": "tester",
```
Comment (funkyboy) [inline Spec/PushChannel.swift]: probably better to reuse `rest.options.clientId`

File: Spec/PushChannel.swift [hunk 3]
```diff
@@ -0,0 +1,330 @@
...
+                it("should not accept both deviceId and clientId params at the same time") {
+                    let params = [
+                        "deviceId": "x",
+                        "clientId": "y"
+                    ]
+                    let channel = rest.channels.get("foo")
+                    expect { try channel.push.listSubscriptions(params) { _, _ in } }.to(throwError { (error: NSError) in
+                        expect(error.code).to(equal(ARTDataQueryError.invalidParameters.rawValue))
+                    })
+                }
```
Comment (funkyboy) [inline Spec/PushChannel.swift]: Please add a test in which you actually subscribe and then you check that the result of `listSubscriptions` actually includes the result of the subscription.

File: Spec/PushChannel.swift (hunk 1 above)
Comment (ricardopereira) [reply Spec/PushChannel.swift]: Fixed 2dba0b0 👍

File: Source/ARTPushChannel.m [hunk 4]
```diff
@@ -174,23 +182,24 @@ - (void)listSubscriptions:(NSDictionary<NSString *, NSString *> *)params callbac
...
+    return YES;
 }
 
-- (ARTDeviceDetails *)getDevice:(void(^_Nullable)(ARTErrorInfo *_Nullable))callback {
-    ARTDeviceDetails *device = [_channel device];
-    if (!device) {
+- (ARTLocalDevice *)getDevice:(void(^_Nullable)(ARTErrorInfo *_Nullable))callback {
+    ARTLocalDevice *device = [_channel device];
+    if (![device isRegistered]) {
         if (callback) callback([ARTErrorInfo createWithCode:0 message:@"cannot use device before ARTRest.push.activate has finished"]);
```
[the remark this answers is not in the document]
Comment (ricardopereira) [reply Source/ARTPushChannel.m]: Accepted acd4100 👍

File: Source/ARTPushChannel.m [hunk 5]
```diff
@@ -146,26 +150,30 @@ - (void)unsubscribeClient:(void(^_Nullable)(ARTErrorInfo *_Nullable))callback {
     }];
 }
 
-- (void)listSubscriptions:(void(^)(ARTPaginatedResult<ARTPushChannelSubscription *> *_Nullable, ARTErrorInfo *_Nullable))callback {
-    [self listSubscriptions:nil callback:callback];
-}
+- (BOOL)listSubscriptions:(NSDictionary<NSString *, NSString *> *)params callback:(void(^)(ARTPaginatedResult<ARTPushChannelSubscription *> *_Nullable, ARTErrorInfo *_Nullable))callback error:(NSError *_Nullable *_Nullable)errorPtr {
```
[the remark this answers is not in the document]
Comment (ricardopereira) [reply Source/ARTPushChannel.m]: It has a `BOOL` because it's how ObjC handle errors. We should respect that for good Swift/ObjC interoperability. An ObjC method with an `NSError **` as last parameter and a BOOL return type will bridge to a Swift method that throw an error.

File: Spec/PushChannel.swift (hunk 3 above)
Comment (ricardopereira) [reply Spec/PushChannel.swift]: Done 720d602 but it doesn't pass. I already reported that issue in Slack.

**Comment by ricardopereira** [comment]
`should return a paginated result with PushChannelSubscription` still fails with "_40100: push not enabled for this channel_"

**Comment by ricardopereira** [comment]
Rebased with `push` branch.

**Comment by funkyboy** [comment]
@ricardopereira when you pull down this branch to run it locally it throws a bunch of compilation errors
screen shot 2018-06-12 at 16 51 04

**Comment by ricardopereira** [comment]
@funkyboy You're working with Xcode 9.3?

**Comment by funkyboy** [comment]
@ricardopereira no, 9.2. Afair you said you didn’t upgrade any project settings.

**Comment by ricardopereira** [comment]
@funkyboy I did not update the project settings, I'm only using Xcode 9.3 https://github.com/ably/ably-ios/pull/709#discussion_r186029445

**Comment by funkyboy** [comment]
@ricardopereira Yup, the point is that it doesn’t compile on 9.2 :(
Anyway an upgrade is on the way, so this will soon be a non problem.

**Comment by ricardopereira** [comment]
@funkyboy I think it's not a big deal. This won't affect users because it only affects tests and even so this is still in beta, from what I know.

File: Spec/PushChannel.swift (hunk 3 above)
Comment (funkyboy) [reply Spec/PushChannel.swift]: If you put a breakpoint on [this line](https://github.com/ably/ably-ios/commit/720d602766f712a8ace8bb4d7d75ac667fe4b2ea#diff-d254ef992ef12123539ed0708d7375d1R337) you'll get

```
(lldb) po channel.name
"test-2-pushenabled:foo"

(lldb) 
```

Comment (funkyboy) [reply Spec/PushChannel.swift]: @ricardopereira quite sure it's due to this https://github.com/ably/ably-ios/blob/push-channels/Spec/TestUtilities.swift#L100

**Comment by funkyboy** [comment]
@ricardopereira FYI I cherry-picked this commit https://github.com/ably/ably-ios/commit/1845218b8ea0f3aa3ca204fd6cdef499d0a8b159 to both `push` and `push-channels`. Now Travis kicks in.

**Comment by funkyboy** [comment]
@ricardopereira also, there's a consistent failure on this line https://github.com/ably/ably-ios/blob/push-channels/Spec/PushActivationStateMachine.swift#L584

Likely due to the fact that the previous test doesn't have a 
`defer { rest.device.setAndPersistIdentityTokenDetails(nil) }`

**Comment by funkyboy** [comment]
Rebased on `push` now.

File: Spec/PushChannel.swift (hunk 3 above)
Comment (funkyboy) [reply Spec/PushChannel.swift]: Fixed in https://github.com/ably/ably-ios/pull/708/commits/02b4d05740d7edf1340f051e1bc69853db8a79cb
